#!/bin/bash
# OC environment setup
# usage:  . myoc

export OC_INST=/users/rsg/ach/scratch_local/beam-workspace/oc-cci/oc-pml-inst

export OC_LOG=$OC_INST/log

mkdir -p $OC_INST/log
mkdir -p $OC_INST/requests

export OC_PRODUCTION_JAR=$OC_INST/lib/cpt.jar
export OC_BEAM_VERSION=beam-4.11.1
export OC_CALVALUS_VERSION=calvalus-1.8

export PYTHONPATH=$OC_INST:$OC_INST/src:$PYTHONPATH
export PATH=$OC_INST/bin:$PATH

PS1="\[\e]0;\u@\h: \w\a\]\[\e[1;32m\]\u \[\e[1;34m\]\w\[\e[0m\] \[\e[0;31m\](OC)\[\e[0m\]$ "

echo "using OC instance $OC_INST"
